<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Push Notifications for Magento 2
*/
?>
<?php /** @var $block \Amasty\PushNotifications\Block\BaseUrl */ ?>
<!-- Using global js vars to get access to magento base url for firebase component registration -->
<script>
    window.firebaseUrl = <?= json_encode($block->getBaseUrl()); ?>
</script>
